Addition of a new display to see the server name easily
fireeye/HXTool pull request #113
Opened 2022-09-14 08:02 UTC by Jilijou

Adding a new object displaying the current profile name.
NEW :
- getHx_name() > new function + reference
- hx_name-placeholder & fe-top-nav__bar-right-item > new list object + css style

MODIFIED :
- .fe-top-nav__topnav .fe-top-nav__bar > css : Added padding right
- profile() > Added a different return when logged in
- .hxtool_topnav_mainbutton:hover > Modified so it only affects the buttons

![image](https://user-images.githubusercontent.com/86848514/190095177-27bf76a3-ca06-4097-96dd-ced7a57cd801.png)

2022-09-14 08:04 UTC, Jilijou commented
Note :
This pull request is here to answer to this enhancement request
https://github.com/fireeye/HXTool/issues/103

2022-09-15 18:35 UTC, B0fH commented
Hi @JilianJouault -
 Thank you for posting this, much appreciated! May I suggest that it might make more sense to store the profile name in session[] as opposed to querying the /profile API on every page load. You could simply add (to this block here https://github.com/fireeye/HXTool/blob/master/hxtool.py#L505):
`
session["profile_name"] = ht_profile["hx_name"]
`
and in your Javascript
`
$('#hx_name-placeholder').text({{session['profile_name']}});
`

Thanks,
 Elazar

2022-09-16 15:35 UTC, B0fH requested changes
Hi @Jilijou -
 Kindly see my comments below. Once you've added the profile name to session, you can do away with the API call code, as I've noted below.

Thanks,
 Elazar

2022-09-16 15:35 UTC, B0fH commented on hxtool_api.py
> +			return json.dumps({'data_count' :  len(profiles), 'data' : profiles})
Remove this change altogether as we're now storing the profile name in session

2022-09-16 15:35 UTC, B0fH commented on templates/layout.html
> +		}
You can remove this as well.

2022-09-16 15:35 UTC, B0fH commented on templates/layout.html
> +			getHx_name();
Change this to:
`
$('#hx_name-placeholder').text({{session['ht_hx_name']}});
`

2022-09-19 07:20 UTC, Jilijou commented
Hello @B0fH,
I just made the modification and it still works 🎉 Proof that I did not fully understand how requests work... I'll need to make a bit more research on that.

Hope it's all good now,
Jilian

2022-09-19 13:49 UTC, B0fH approved these changes
Looks good, thank you!

2022-09-19 13:49 UTC, merged