Prevent use of TLS 1.1
fireeye/HXTool pull request #92
Opened 2021-11-17 15:13 UTC by moshekaplan

2021-12-13 22:33 UTC, B0fH commented
Hi @moshekaplan - 
 Kindly review the comment I've posted above.

Thanks,
 Elazar

2021-12-14 00:36 UTC, moshekaplan commented
> Hi @moshekaplan - Kindly review the comment I've posted above.
> 
> Thanks, Elazar

Which comment is this? I don't see any.

2021-12-14 23:04 UTC, B0fH requested changes
Hi @moshekaplan -
 Kindly restore the newline and then I can go ahead and merge this.
Thanks,
 Elazar

2021-12-15 01:46 UTC, moshekaplan commented on hxtool.py
> -	app_init(debug = False)
I'll try to figure out how. Github's online editor automatically added the newline at the end.

2021-12-15 01:54 UTC, moshekaplan commented on hxtool.py
> -	app_init(debug = False)
Fixed

2021-12-15 04:59 UTC, merged