Don't use insecure SSL ciphers
fireeye/HXTool pull request #93
Opened 2021-11-17 15:58 UTC by moshekaplan

Note about the `!SHA1:!SHA256:!SHA384` at the end:

"You can use !SHA1:!SHA256:!SHA384 to disable all CBC mode ciphers. There are some non-CBC false positives that will also be disabled (RC4, NULL), but you probably also want to disable them anyway.
Note that while GCM and CHACHA20 ciphers have SHA* in their name, they're not disabled because they use their own MAC algorithm. The SHA* in their name is for the PRF, not the MAC"

https://security.stackexchange.com/questions/166484/how-to-disable-cbc-mode-ciphers

2021-12-13 22:33 UTC, B0fH commented
Hi @moshekaplan -
Kindly review the comment I've posted above.

Thanks,
Elazar

2021-12-14 00:36 UTC, moshekaplan commented
> Hi @moshekaplan - Kindly review the comment I've posted above.
> 
> Thanks, Elazar

Which comment is this? I don't see any.

2021-12-14 23:04 UTC, B0fH requested changes
Hi @moshekaplan -
Kindly restore the newline and then I can go ahead and merge this.
Thanks,
Elazar

2021-12-15 01:53 UTC, moshekaplan commented on hxtool.py
> -	app_init(debug = False)
Fixed

2021-12-15 05:02 UTC, merged